name: Create PR from cloud-ci
on:
  push:
    branches:
      - cloud-ci
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: api-create-pr-${{ github.head_ref || github.run_id }}
defaults:
  run:
    shell: bash

jobs:
  create-pr:
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_AUTHOR_NAME: Synqlair
      CI_COMMIT_AUTHOR_EMAIL: ci@synq.io
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Check if PR exists
      id: check
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        prs=$(gh pr list \
            --repo "$GITHUB_REPOSITORY" \
            --head 'cloud-ci' \
            --base 'main' \
            --json title \
            --jq 'length')
        if ((prs > 0)); then
            echo "skip=true" >> "$GITHUB_OUTPUT"
        fi
    - name: Create pull request
      if: '!steps.check.outputs.skip'
      run: |
        gh pr create -B main -H cloud-ci --title 'Publish protos' --body ':rocket: Publish the latest proto changes.'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
